### ISSUE TITLE
READ -- staff

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/nutshell-renaissance-fair#10]
# User Story
As a user I want to see my staff members printed to the page.

# AC
**WHEN** I navigate to the staff section
**THEN** I should see my staff members printed to cards on the page

# Dev Notes
* write a function with a promise constructor that will use an axios get call to return a promise of the staff data.
* convert the response to an array of staff objects
* export the axios call function and call it in a new component (staff)
* in this function call the getStaff function and with the returned promise, build a domString that will contain all html for the staff page except for each individual staff member.
* create a new component for an individual staff member with a single function that builds a domString for an individual staff member card.
* within the staff component domString builder, use a forEach loop to loop over the objects of staff members and call the individual staff member builder to pass in each staff member.

**Comment by ivannio** [comment]
![staff page](https://user-images.githubusercontent.com/21040719/68729837-ab901f00-0590-11ea-9b46-f8104b763a91.png)

Staff page mockup
