### ISSUE TITLE
CREATE - Staff

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/nutshell-renaissance-fair#11]
# UserStory
* When the user clicks on the "add staff member" button, a modal should pop up with the general information of (name, phone, email, employee ID, role, location). They should then be able to fill in the details of each part and click the "save changes" button which will add the new card of the new staff member to the page.

# AC
**WHEN** the "add staff member" button is pressed
**THEN** a modal will pop up with blank input fields of the above data fields
**AND** after completion when the the "save changes" button is clicked
**THEN** the new information will be printed on a card with the other cards on the page.

# DevNotes
* An "add staff member" button will be centered at the top of the page underneath the h1 tag.
* All buttons will be the "primary" selector button from bootstrap.
* There will be a click event on the the "add staff member" button that will trigger a modal with 7 input fields. 
* A second click event will be on the "save and add" button in the modal which will trigger the function addNewStaffMember.
* The addNewStaffMemberfunction inside of newStaff.js will define a new object from the modal inputs like below:
```
const newStaffMember = {
    name = '',
    phone = '',
    email = '',
    imageUrl= '',
    role = '',
    employeeIdNumber = '',
    location = '',
};
```
* The newStaffMember object will be passed as a parameter when calling the postNewStaffMember axios post function in staffData.js. 
* The addNewStaffMember function will then call the main printStaff function from printStaff.js and then hide the modal.
* Inside the staffData.js file the postNewStaffMember axios call will post the results to the firebase like seen here:
```
const addNewStaff = (newStaffMember) => axios.post(`${baseUrl}/staff.json`, addNewStaff);
```
* Once firebase is updated with the axios post call the new array of objects from firebase will then print to the DOM with the new staff member card printed.

**Comment by ivannio** [comment]
![staff page](https://user-images.githubusercontent.com/21040719/68729837-ab901f00-0590-11ea-9b46-f8104b763a91.png)

Staff page mockup
