### ISSUE TITLE
DELETE - Staff

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/nutshell-renaissance-fair#12]
# User Story
As a user, if I am logged in, I should be able to delete a staff member from the staff page.

# AC
WHEN: the page loads a gallery of staff members should appear. 
THEN: the user hovers over a staff member, a delete button should appear.
THEN: if the user is logged in, the user can click on the delete button.
THEN:  the staff member is deleted from the page and the database.

# Dev Notes
Write an event listener so that -- on hover over a single staff card -- a delete button/link appears at the bottom of the card.
When the delete button/link is clicked, another event listener is fired that accesses firebase so that the staff member is deleted from DOM and from firebase.
* The delete event listener will call a function that:
  1)Grabs the staff member's id.
  2) Makes an axios call to firebase to remove the staff member's data.  The axios call should be in 
      the staffsData.js file:
     const deleteStaffCard = (staffMemberId) =>       axios.delete(`${baseUrl}/staff/${staffMemberId}.json`);
  3) Call the printStaffCard() function to display the updated staff members to the page.

**Comment by ivannio** [comment]
![staff page](https://user-images.githubusercontent.com/21040719/68729837-ab901f00-0590-11ea-9b46-f8104b763a91.png)

Staff page mockup
