### ISSUE TITLE
READ - Souvenirs

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#13]
# User Story
As a user I want to see my available souvenirs printed to the page.

# AC
**WHEN** I navigate to the souvenirs section
**THEN** I should see my souvenirs printed to cards on the page

# Dev Notes
* write a function with a promise constructor that will use an axios get call to return a promise of the souvenirs data.
* convert the response to an array of souvenir objects
* export the axios call function and call it in a new component (souvenirs)
* in this function call the getSouvenirs function and with the returned promise, build a domString that will contain all html for the souvenirs page except for each individual souvenir.
* create a new component for an individual souvenir with a single function that builds a domString for an individual souvenir card.
* within the souvenirs component domString builder, use a forEach loop to loop over the objects of souvenirs and call the individual souvenir builder to pass in each item.

**Comment by ivannio** [comment]
![souvenirs](https://user-images.githubusercontent.com/21040719/68730570-aa5ff180-0592-11ea-8fc3-0b9e1b1f91e1.png)

Souvenir page mockup
