### ISSUE TITLE
CREATE - Souvenirs

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#14]
# UserStory
* When the user clicks on the "add souvenir" button, a modal should pop up with the general information of imageUrl, price, type, name, description, quantity, and location. They should then be able to fill in the details of each part and click the "save changes" button which will add the new card of the new souvenir item to the page.

# AC
**WHEN** the "add souvenir button" is pressed
**THEN** a modal will pop up with blank input fields of the above data fields
**AND** after completion when the the "save changes" button is clicked
**THEN** the new information will be printed on a card with the other cards on the page.

# DevNotes
* An "add souvenir" button will be centered at the top of the page underneath the h1 tag.
* All buttons will be the "primary" selector button from bootstrap.
* There will be a click event on the the "add Souvenir" button that will trigger a modal with 7 input fields. 
* A second click event will be on the "save and add" button in the modal which will trigger the function addNewSouvenir.
* The addNewSouvenir function inside of newSouvenir.js will define a new object from the modal inputs like below:
```
const newSouvenir = {
    name = '',
    imageUrl = '',
    description = '',
    price = '',
    type = '',
    quantitiy = ,
    location = '',
};
```
* The newSouvenir object will be passed as a parameter when calling the postNewSouvenir axios post function in souvenirData.js. 
* The addNewSouvenir function will then call the main printSouvenirs function from printSouvenirs.js and then hide the modal.
* Inside the souvenirData.js file the postNewSouvenir axios callwill post the results to the firebase like seen here:
```
const addNewSouvenir = (newSouvenir) => axios.post(`${baseUrl}/souvenirs.json`, newSouvenir);
```
* Once firebase is updated with the axios post call the new array of objects from firebase will then print to the DOM with the new souvenir card printed.

**Comment by ivannio** [comment]
![souvenirs](https://user-images.githubusercontent.com/21040719/68730570-aa5ff180-0592-11ea-8fc3-0b9e1b1f91e1.png)

Souvenir page mockup
