### ISSUE TITLE
UPDATE - Souvenirs

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#15]
#  User Story
As a user, when i  should be able to update souvenirs i want and when hover over each cards I should see update button.
# AC
**When** update button is clicked,
**Then** bootstrap modal popup with corresponding data from firebase database populate in the fields( id, imageUrl, price, type, name, description, stockAmount, isStocked, location) and save changes button
**And** when save changes button is clicked, update should be made both in firebase database and dom
# Dev Notes
* Add bootstrap modal with input field for id, imageUrl, price, type, name, description, stockAmount, isStocked, location to html file
* Create `updateSouvenirsData.js` file and import axios and `apiKeys.json file`.
* Store request to firebase database in variable called baseUrl as 
```const baseUrl = apiKeys.firebaseKeys.databaseURL;```
* Create an `updateSouvenirs` function that takes souvenirsId as parameter
* Inside `updateSouvenirsData.js` file create `updatedSouvenirs` function. as
```
const updatedSouvenirs= (souvenirsId, updatedSouvenirs) => axios.put(`${baseUrl}/souvenirsId.json`, updatedSouvenirs);
```
* Export `updateSouvenirs` 
* Import `updateSouvenirs` in `theSouvenirs.js` file
* Create `finalSouvenirsUpdate` function inside `theSouvenirs.js` file that takes `souvenirsId` as parameter for update
* Inside finalSouvenirsUpdate function call `buildSouvenirs` function to display update on dom

**Comment by ivannio** [comment]
![souvenirs](https://user-images.githubusercontent.com/21040719/68730570-aa5ff180-0592-11ea-8fc3-0b9e1b1f91e1.png)

Souvenir page mockup

**Comment by zoeames** [comment]
Axios URL above isn’t quite right.  It should be this:
```
const updatedSouvenirs= (souvenirId, updatedSouvenir) => axios.put(`${baseUrl}/souvenirs/${souvenirId}.json`, updatedSouvenir);
```
