### ISSUE TITLE
DELETE - Souvenirs

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#16]
# User Story

As a user, if I am logged in, I should be able to delete a souvenir from the souvenirs page.

# AC

WHEN: the page loads a gallery of souvenirs should appear.
THEN: the user hovers over a souvenir, a delete button should appear.
THEN: if the user is logged in, the user can click on the delete button.
THEN: the souvenir is deleted from the page and the database.

# Dev Notes

Write an event listener so that -- on hover over a single souvenir  card -- a delete button/link appears at the bottom of the card.
When the delete button/link is clicked, another event listener is fired that accesses firebase so that the souvenir is deleted from DOM and from firebase.

The delete event listener will call a function that:
1)Grabs the souvenir's id.
2) Makes an axios call to firebase to remove the souvenir's data. The axios call should be in
the souvenirData.js file:
const deleteSouvenirCard = (souvenirId) => axios.delete(${baseUrl}/souvenirs/${souvenirId}.json);
3) Call the showSouvenirs() function to display the updated souvenirs to the page.

**Comment by ivannio** [comment]
![souvenirs](https://user-images.githubusercontent.com/21040719/68730570-aa5ff180-0592-11ea-8fc3-0b9e1b1f91e1.png)

Souvenir page mockup
