### ISSUE TITLE
UPDATE - Staff

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/nutshell-renaissance-fair#17]
#  User Story
As a user, when i  should be able to update souvenirs i want and when hover over each cards I should see update button.
# AC
**When** update button is clicked,
**Then** bootstrap modal popup with corresponding data from firebase database populate in the fields( id, name, price, description, location, type, imageUrl, stockAmount, isStocked) and save changes button
**And** when save changes button is clicked, update should be made both in firebase database and dom
# Dev Notes
* Add bootstrap modal with input field for id, name, price, description, location, type, imageUrl, stockAmount, isStocked to html file
* Create `updateStaffData.js` file and import axios and `apiKeys.json file`.
* Store request to firebase database in variable called baseUrl as 
```const baseUrl = apiKeys.firebaseKeys.databaseURL;```
* Create an `updateStaff` function that takes staffId as parameter
* Inside `updateStaffData.js` file create `updatedStaff` function. as
```
const updatedStaff= (staffId, updatedStaff) => axios.put(`${baseUrl}/staffId.json`, updatedStaff);
```
* Export `updateSouvenirs` 
* Import `updateStaff` in `theStaff.js` file
* Create `finalStaffUpdate` function inside `theStaff.js` file that takes `staffId` as parameter for update
* Inside finalStaffUpdate function call `buildStaff` function to display update on dom

**Comment by ivannio** [comment]
![staff page](https://user-images.githubusercontent.com/21040719/68729837-ab901f00-0590-11ea-9b46-f8104b763a91.png)

Staff page mockup

**Comment by zoeames** [comment]
Axios URL above isn’t quite right. Should be this:
```const updatedStaff= (staffId, updatedStaff) => axios.put(`${baseUrl}/staffs/${staffId}.json`, updatedStaff);```
