### ISSUE TITLE
Update-Shows

### ISSUE THREAD

**Issue by ygitore** [nss-evening-cohort-10/nutshell-renaissance-fair#18]
#  User Story
As a user, when i  should be able to update souvenirs i want and when hover over each accordion items I should see update button.
# AC
**When** update button is clicked,
**Then** bootstrap modal popup with corresponding data from firebase database populate in the fields( Id, Name, date, ticketPrice, location, ImageUrl, description) and save changes button
**And** when save changes button is clicked, update should be made both in firebase database and dom
# Dev Notes
* Add bootstrap modal with input field for Id, Name, ticketPrice, location, ImageUrl, description, and date as date time format
to html file
* Create `updateShowsData.js` file and import axios and `apiKeys.json file`.
* Store request to firebase database in variable called baseUrl as 
```const baseUrl = apiKeys.firebaseKeys.databaseURL;```
* Create an `updateShows` function that takes showsId as parameter
* Inside `updateShowsData.js` file create `updatedShows` function. as
```
const updatedSouvenirs= (showsId, updatedShowsId) => axios.put(`${baseUrl}/showsId.json`, updatedShowsId);
```
* Export `updateShows` 
* Import `updateShows` in `theShows.js` file
* Create `finalShowsUpdate` function inside `theShows.js` file that takes `showsId` as parameter for update
* Inside `finalShowsUpdate` function call `buildShows` function to display update on dom

**Comment by yitbarekgitore** [comment]
#  User Story
As a user, i should be able to edit and update shows i want.
# AC
** When ** edit button is clicked,
** Then ** bootstrap modal popup with data from firebase database populated in fields(Name, Image, description, ..) and save button
# Dev Notes
* get bootstrap modal from `https://www.bootstrap.com` add to html file
* Create component with method that grabs data from firebase database

**Comment by ivannio** [comment]
![shows-page](https://user-images.githubusercontent.com/21040719/68729249-150f2e00-058f-11ea-91dc-677b71021495.png)

Shows page mockup

**Comment by zoeames** [comment]
Axios url isn’t quite right.  Also looks like you should change the name of that.  Maybe to something like this:
```const updatedShows= (showsId, updatedShowsId) => axios.put(`${baseUrl}/shows/${showsId}.json`, updatedShowsId);```
