### ISSUE TITLE
CREATE - Food

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#20]
# UserStory
* When the user clicks on the "add food item" button, a modal should pop up with the general information of (imageUrl, price, type, name, description, quantity, and location). They should then be able to fill in the details of each part and click the "save changes" button which will add the new card of the new souvenir item to the page.

# AC
**WHEN** the "add food" button is pressed
**THEN** a modal will pop up with blank input fields of the above data fields
**AND** after completion when the the "save changes" button is clicked
**THEN** the new information will be printed on a card with the other cards on the page.

# DevNotes
* An "add food item" button will be centered at the top of the page underneath the h1 tag.
* All buttons will be the "primary" selector button from bootstrap.
* There will be a click event on the the "add food item" button that will trigger a modal with 7 input fields. 
* A second click event will be on the "save and add" button in the modal which will trigger the function addFoodItem.
* The addFoodItem inside of newFood.js will define a new object from the modal inputs like below:
```
const newFood = {
    name = '',
    phone = '',
    email = '',
    imageUrl= '',
    role = '',
    employeeIdNumber = '',
    location = '',
};
```
* The newFood object will be passed as a parameter when calling the postNewFood axios post function in foodData.js. 
* The addFoodItem function will then call the main printFood function from printFood.js and then hide the modal.
* Inside the foodData.js file the postNewFood axios call will post the results to the firebase like seen here:
```
const addNewFood = (newFood) => axios.post(`${baseUrl}/food.json`, newFood);
```
* Once firebase is updated with the axios post call the new array of objects from firebase will then print to the DOM with the new food item card printed.

**Comment by ivannio** [comment]
![food](https://user-images.githubusercontent.com/21040719/68730376-2c9be600-0592-11ea-8735-8c082961352e.png)

food page mockup
