### ISSUE TITLE
CREATE - Shows

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#21]
# UserStory
* When the user clicks on the "add show" button, a modal should pop up with the general information of (imageUrl, ticketPrice, name, description, date, time, and location). They should then be able to fill in the details of each part and click the "save changes" button which will add the new card of the new show to the page.

# AC
**WHEN** the "add show" button is pressed
**THEN** a modal will pop up with blank input fields of the above data fields
**AND** after completion when the the "save changes" button is clicked
**THEN** the new information will be printed to the accordion with the other show dates on the page.

# DevNotes
* An "add show" button will be centered at the top of the page underneath the h1 tag.
* All buttons will be the "primary" selector button from bootstrap.
* There will be a click event on the the "add show" button that will trigger a modal with 7 input fields. 
* A second click event will be on the "save and add" button in the modal which will trigger the function addNewShow.
* The addNewShowfunction inside of newShow.js will define a new object from the modal inputs like below:
```
const newShow = {
    name = '',
    date = '',
    time = '',
    ticketPrice = '',
    imageUrl= '',
    description = ,
    location = '',
};
```
* The newShow object will be passed as a parameter when calling the postNewShow axios post function in showData.js. 
* The addNewShow function will then call the main printShows function from printSouvenirs.js and then hide the modal.
* Inside the showData.js file the postNewShow axios call will post the results to the firebase like seen here:
```
const addNewShow= (newShow) => axios.post(`${baseUrl}/show.json`, newShow);
```
* Once firebase is updated with the axios post call the new array of objects from firebase will then print to the DOM with the new show card printed.

**Comment by ivannio** [comment]
![shows-page](https://user-images.githubusercontent.com/21040719/68729249-150f2e00-058f-11ea-91dc-677b71021495.png)

Shows page mockup

**Comment by zoeames** [comment]
Post should be to shows.json not show.json
