### ISSUE TITLE
DELETE - Food

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/nutshell-renaissance-fair#22]
# User Story

As a user, if I am logged in, I should be able to delete a food item from the staff page.

# AC

WHEN: the page loads a gallery of food item cards should appear.
THEN: the user hovers over a food item, a delete button should appear.
THEN: if the user is logged in, the user can click on the delete button.
THEN: the food item is deleted from the page and the database.

# Dev Notes

Write an event listener so that -- on hover over a single food card -- a delete button/link appears at the bottom of the card.
When the delete button/link is clicked, another event listener is fired that accesses firebase so that the food item is deleted from DOM and from firebase.

The delete event listener will call a function that:
1)Grabs the food item's id.
2) Makes an axios call to firebase to remove the food item's data. The axios call should be in
the foodData.js file:
const deleteFoodCard = (foodItemId) => axios.delete(${baseUrl}/foods/${foodItemId}.json);
3) Call the showFood() function to display the updated food items to the page.

**Comment by ivannio** [comment]
![food](https://user-images.githubusercontent.com/21040719/68730376-2c9be600-0592-11ea-8735-8c082961352e.png)

food page mockup

**Comment by zoeames** [comment]
Collection here is foods not food
