### ISSUE TITLE
DELETE - Shows

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/nutshell-renaissance-fair#23]
# User Story

As a user, if I am logged in, I should be able to delete a show from the shows page.

# AC

WHEN: the page loads an accordion style display of shows should appear.
THEN: the user hovers over a show, a delete button should appear.
THEN: if the user is logged in, the user can click on the delete button.
THEN: the show is deleted from the page and the database.

# Dev Notes

Write an event listener so that -- on hover over a single show card -- a delete button/link appears at the bottom of the card.
When the delete button/link is clicked, another event listener is fired that accesses firebase so that the show is deleted from DOM and from firebase.

The delete event listener will call a function that:
1)Grabs the show's id.
2) Makes an axios call to firebase to remove the show's data. The axios call should be in
the showData.js file:
const deleteShowCard = (showId) => axios.delete(${baseUrl}/shows/${showId}.json);
3) Call the showShows() function to display the updated shows to the page.

**Comment by ivannio** [comment]
![shows-page](https://user-images.githubusercontent.com/21040719/68729249-150f2e00-058f-11ea-91dc-677b71021495.png)

Shows page mockup
