### ISSUE TITLE
Data Files -  Souvenirs

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#24]
# UserStory
* none

# AC
**WHEN** you pull up the souvenirs.json file
**THEN** there should be data inside of the file

# DevNotes
* Add a souvenirs.json file and create the data needed for the souvenirs page.
* Import the data into the correct section of the firebase database.

**Comment by zoeames** [comment]
Can you add in a sample souvenir object here - that way you make sure you have all the right keys.
