### ISSUE TITLE
Data Files - Food

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#25]
# UserStory
* none

# AC
**WHEN** you pull up the foods.json file
**THEN** there should be data inside of the file

# DevNotes
* Add a foods.json file and create the data needed for the food page.
* Import the data into the correct section of the firebase database.
* Data should contain the following key value pairs:
```json
{
	"food1": {
		"name": "Turkey Leg",
		"description": "A massive leg of juicy turkey that will satisfy even the hungriest of fest-goers!",
		"price": 8,
		"location": "Concessions stand 1",
		"type": "food",
		"quantity": 79,
		"imageUrl": "http://www.pics-of-legs.org/animal-legs/turkey-legs/big-juicy-mfin-turkey-leg.jpg"
	}
}

**Comment by zoeames** [comment]
Can you add in a sample food object here? That way we can make sure you have all the right keys

**Comment by ivannio** [comment]
> Can you add in a sample food object here? That way we can make sure you have all the right keys

done!
