### ISSUE TITLE
Data Files - Shows

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#26]
# UserStory
* none

# AC
**WHEN** you pull up the shows.json file
**THEN** there should be data inside of the file

# DevNotes
* Add a shows.json file and create the data needed for the shows page.
* Import the data into the correct section of the firebase database.

**Comment by zoeames** [comment]
Can you add in a sample shows object here?  That way we can make sure you have all the right keys
