### ISSUE TITLE
Data File - Staffs

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#27]
# UserStory
* none

# AC
**WHEN** you pull up the staff.json file
**THEN** there should be data inside of the file

# DevNotes
* Add a staff.json file and create the data needed for the staff page.
{
  "staff1": {
    "name": "",
    "phone": "",
    "imageUrl": "",
    "email": "",
    "employeeId": "",
    "role": "",
    "location": ""
  }
}
* Import the data into the correct section of the firebase database.

**Comment by zoeames** [comment]
Can you add in a sample staff object here?  That way we can make sure you have all the right keys
