### ISSUE TITLE
Data Files - base.json

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#28]
# UserStory
* none

# AC
**WHEN** you pull up the basejson file
**THEN** there should have the 4 compenents to the base (food, shows, souvenirs, staff)

# DevNotes
* Add a base.json file and create the data needed for the souvenirs page.
* Import the data into the firebase database.

**Comment by zoeames** [comment]
For these collection names put an s at the end of each one.  It sounds funny for staff and foods but will make your lives easier with naming.  So your base file will look like this:
```
{
“foods”: “chicken”,
“shows”: “jousting”,
“souvenirs”: “shoes”,
“staffs”: “Greg”
}
```
