### ISSUE TITLE
Update - Food

### ISSUE THREAD

**Issue by ygitore** [nss-evening-cohort-10/nutshell-renaissance-fair#29]
#  User Story
As a user, when i  should be able to update souvenirs i want and when hover over each cards I should see update button.
# AC
**When** update button is clicked,
**Then** bootstrap modal popup with corresponding data from firebase database populate in the fields( id, name, price, description, location, type, imageUrl, stockAmount, isStocked) and save changes button
**And** when save changes button is clicked, update should be made both in firebase database and dom
# Dev Notes
* Add bootstrap modal with input field for id, name, price, description, location, type, imageUrl, stockAmount, isStocked to html file
* Create `updateFoodData.js` file and import axios and `apiKeys.json file`.
* Store request to firebase database in variable called baseUrl as 
```const baseUrl = apiKeys.firebaseKeys.databaseURL;```
* Create an `updateFood` function that takes foodId as parameter
* Inside `updateFoodData.js` file create `updatedFood` function that takes foodId and updatedFood as parameter
```
const updatedFood= (foodId, updatedFood) => axios.put(`${baseUrl}/foodId.json`, updatedFood);
```
* Export `updateFood` 
* Import `updateFood` in `theFood.js` file
* Create `finalFoodUpdate` function inside `theFood.js` file that takes `foodId` as parameter for update
* Inside finalFoodUpdate function call `buildFood` function to display update on dom

**Comment by ivannio** [comment]
![food](https://user-images.githubusercontent.com/21040719/68730376-2c9be600-0592-11ea-8735-8c082961352e.png)

food page mockup

**Comment by zoeames** [comment]
This url isn’t quite right.  Should be:
```const updatedFood= (foodId, updatedFood) => axios.put(`${baseUrl}/foods/${foodId}.json`, updatedFood)```
