### ISSUE TITLE
HOME DASHBOARD

### ISSUE THREAD

**Issue by denzelb5** [nss-evening-cohort-10/nutshell-renaissance-fair#32]
# User Story:
As a user, when the page loads, I should see a home page with four categories: shows, souvenirs, food,  and staff.  There should also be a footer at the bottom with the company name, copyright logo and address.

# AC:
WHEN: the page loads, 
THEN: 4 cards will appear representing 4 categories:  shows, souvenirs, food, and staff.  Each card should have the name of category and a background image. There should be a company name, copyright logo, and address in the footer of the page.

# Dev Notes:
Use bootstrap cards to represent the four categories with a bootstrap class of col-4 so that two cards appear per row.
The footer contents -- company name with copyright logo attached with address listed underneath -- should be centered on the bottom of the page.
Each of the four cards should have their own event listener.  Upon click, the home page div will be hidden and the targeted category div will be displayed regardless of user login status.

**Comment by ivannio** [comment]
![front page](https://user-images.githubusercontent.com/21040719/68728082-e6438880-058b-11ea-96cf-591dc53cae72.png)

Home page mockup
