### ISSUE TITLE
ERD Part 2

### ISSUE THREAD

**Issue by CharityBunyon** [nss-evening-cohort-10/nutshell-renaissance-fair#74]

**Comment by CharityBunyon** [comment]
<img width="871" alt="Screen Shot 2019-11-23 at 10 37 58 AM" src="https://user-images.githubusercontent.com/52020883/69482162-6d3eff00-0ddd-11ea-990d-6d01ec847458.png">

**Comment by CharityBunyon** [comment]
<img width="853" alt="Screen Shot 2019-11-25 at 7 31 39 PM" src="https://user-images.githubusercontent.com/52020883/69592047-599cbf80-0fba-11ea-87f8-0932fb9e7caf.png">

**Comment by zoeames** [comment]
looks like you have two souvenirs collections here.  the bottom one in this diagram should be souvenirEvents

**Comment by zoeames** [comment]
also change "staff Event" to "staffEvents"

**Comment by zoeames** [comment]
also lets rename the 4 new collections to:
* eventFoods
* eventShows
* eventStaffs
* eventSouvenirs

**Comment by CharityBunyon** [comment]
Zoe we did name them that way.

**Comment by zoeames** [comment]
then just change the erd above to match
