### ISSUE TITLE
Renaissance Fair Events (READ)

### ISSUE THREAD

**Issue by jbkey2015** [nss-evening-cohort-10/nutshell-renaissance-fair#75]
## User Story
**As** a user, I should be able to add Renaissance Fair Events.

## AC
**WHEN** the user goes to the event page
**AND** the user clicks the Add Event button
**THEN** a modal should appear with input fields to add new event.

## Dev Notes

**Setting Up Events Read**
 - [x] Check to make sure the events.json have been made
 - [x] Mak a eventData file in helpers. Within that file should be a function called getEvents that will create a new Promise.

```
import axios from 'axios';
import apiKeys from '../apiKeys.json';

const baseUrl = apiKeys.firebaseKeys.databaseURL;

const getEvents = () => new Promise((resolve, reject) => {
  axios.get(`${baseUrl}/events.json`)
    .then((response) => {
      const theEvents = response.data;
      const events = [];
      Object.keys(theEvents).forEach((fbId) => {
        theEvents[fbId].id = fbId;
        foods.push(theEvents[fbId]);
      });
      resolve(events);
    })
    .catch((error) => reject(error));
});
```

**EventCard Component**
- [x] Make a domstring for the seed data and export that to the Events Component and reference it in the buildEvents function.

**Events Component**
- [x] Within events.js create a function called buildEvent

```
const buildEvents = (uid) => {
  eventData.getEvents(uid)
    .then((boards) => {
      let domString = `<div class="container text-center" style="padding:50px"><button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#addEventModal">
      Add Event
    </button>`;
      domString += '<div id="boardSection" class="d-flex flex-wrap">';
      boards.forEach((board) => {
        domString += EventCard.MakeEventBoard(board);
      });
      domString += '</div>';
      utilities.printToDom('events', domString);
      $('#events').on('click', '.chosen-board', createSingleEvent);
      $('#submitEvent).click(addEvent);
    });
  // .catch((error) => console.error(error));
};
```

- [x] Axios Call to grab items from firebase

```
const getFoodById = (foodId) => axios.get(`${baseUrl}/foods/${foodId}.json`);

```

**Comment by zoeames** [comment]
why are there 2 axios calls in here?  this is an add function - shouldn't there just be a post request?

**Comment by zoeames** [comment]
there are lots of instances of the word "board" in this tickets...seems like a bad copy paste job #awkward
