### ISSUE TITLE
Modify Events

### ISSUE THREAD

**Issue by jbkey2015** [nss-evening-cohort-10/nutshell-renaissance-fair#87]
## User Story
**As a user**, when I am on the Events page I should only be able to modify or delete events I have created.

## AC

**WHEN** I am on the Events page and logged in, I should be able to click on the event(s) 
**THEN** I should click on the edit button.
**AND** edit one or more details of that event (name, location, date). 
**AND** I should not be able to click on an event to modify that I did not create.

## Dev Notes

- [ ] Create axios.put() in eventData.js file
- [ ] Create edit event function in eventData.js file
- [ ] Create event listener on the edit button in eventData.js with the (e.target.id) will be how I capture the event object by id from firebase.
- [ ] Use a modal to show the prepopulated fields for the eventId.
- [ ] Use a button to save the data.
- [ ] Create event listener on the save button in eventData.js this will call the editEvent function
- [ ] update firebase and make sure to call buildEvents function to refresh the eventCard.

**Comment by aleshakay** [comment]
WIP need to check on the files names, and flup on how to target only ones used by UID

**Comment by aleshakay** [comment]
![image](https://user-images.githubusercontent.com/39807157/69588687-04a77c00-0faf-11ea-9ab1-a980e5f237a4.png)

**Comment by aleshakay** [comment]
![image](https://user-images.githubusercontent.com/39807157/69588712-230d7780-0faf-11ea-8590-e8f35ebe445a.png)
