### ISSUE TITLE
Event Detail Page

### ISSUE THREAD

**Issue by jbkey2015** [nss-evening-cohort-10/nutshell-renaissance-fair#88]
## User Story
**As a user**, I should be able to see a detail page for a specific event.

## AC
WHEN the page loads and the user clicks to view the events dashboard
THEN the user should be able to see a list of all events (cards)
AND the user should be able to perform full CRUD on each event card

## Dev Notes

**In events.js**
- create showSingleEvent function
- create single eventData file in helpers

```

const showSingleEvent = (boardId) => {
  singleData.getSingleEvent(boardId)
    .then((board) => {
      let domString = '<div id="boardSection" class="container"><button class="closeBtn">Close</button>';
      domString += `<button type="button" id="newEvent" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#eventModal">
      Add New Event
    </button></div>`;
      utilities.printToDom('events', domString);
      $('#boardSection').on('click', '.closeBtn', close);
      $('#addNewEvent').attr('newEvent', boardId);
    })
    .catch((error) => console.error(error));
};
```
- have add and delete staff, sourvenirs, food, and shows to the singleEvent function or page.
- call showSingleEvent in buildEvents function

**Comment by zoeames** [comment]
shouldn't this be calling the smash function?
