### ISSUE TITLE
Setup Branch

### ISSUE THREAD

**Issue by phillipsja97** [nss-evening-cohort-10/nutshell-renaissance-fair#9]
# UserStory
* no user story

# AC
**WHEN** you open up VS Code, you should have all of webpack installed
**AND** you should have set up components, helpers, db and styles folder.
**THEN** you should set up the printToDom function in the helpers folder and in the utilities file 
**THEN** set up 5 divs (#boards, #souvenirs #Foods, #Shows, #Staff) in the index.html
**THEN** set up the API keys from firebase.

# DevNotes
* Run the webpack installer
* After setting up the webpack, create the different javascripts folders listed above.
* Create a printToDom function in the utilities file inside of the helpers folders.
* Create five separate div id's inside of index.html as listed above.
* Take the API keys from firebase and setup the apiKeys.json as well as the apiKeys.example.json file and put the apiKeys.json file in the .gitignore file, and leave the strings blank in apiKeys.example.json.

**Comment by zoeames** [comment]
Make sure all your divs have lowercase ids.  Assuming they will but wanted to be explicit
